### ISSUE TITLE
TypeError with python 3.12b1 : type `typing.TypeVar` is not an acceptable base type

### ISSUE THREAD

**Issue by karthiknadig** [python/typing_extensions#243]
```
  File "/<redacted>/.vscode/extensions/ms-python.black-formatter-2023.2.0/bundled/libs/typeguard/__init__.py", line 27, in <module>
    from typing_extensions import Literal
  File "/<redacted>/.vscode/extensions/ms-python.black-formatter-2023.2.0/bundled/libs/typing_extensions.py", line 1174, in <module>
    class TypeVar(typing.TypeVar, _DefaultMixin, _root=True):
TypeError: type 'typing.TypeVar' is not an acceptable base type
```

**Comment by JelleZijlstra** [comment]
Sounds like the tool you're using is bundling some release of typing-extensions. It should update to the latest release. I believe this was broken on 4.4.0 and fixed on 4.6.0.

**Comment by karthiknadig** [comment]
@JelleZijlstra You are right this error is on typing_extension 4.5.0.

**Comment by AlexIca82** [comment]
Dear all, I've got the same error with the MetaGPT code. Could you tell me which actions should I take to solve the issue?

**Comment by AlexWaygood** [comment]
> Dear all, I've got the same error with the MetaGPT code. Could you tell me which actions should I take to solve the issue?

Use typing_extensions>=4.6.0

**Comment by AlexIca82** [comment]
> > Dear all, I've got the same error with the MetaGPT code. Could you tell me which actions should I take to solve the issue?
> 
> Use typing_extensions>=4.6.0

Is this correct?  pip install typing_extension==4.6.0.

Thanks

**Comment by AlexIca82** [comment]
Done, thank you

**Comment by itszn** [comment]
I still get this error on typing_extensions 4.15.0 for Python 3.12.3...
This is breaking jedi for me on this python version.

```
$ python3 -m pip install --upgrade typing_extensions --break-system-packages
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: typing_extensions in /home/nyan/.local/lib/python3.12/site-packages (4.15.0)

$ python3
Python 3.12.3 (main, Aug 14 2025, 17:47:21) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import typing
>>> class TypeVar(typing.TypeVar):
...   pass
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: type 'typing.TypeVar' is not an acceptable base type
```
